backend:
  name: git-gateway
  branch: main

local_backend: true

publish_mode: editorial_workflow

media_folder: 'public' # Media files will be stored in the repo under public/
public_folder: '/' # The src attribute for uploaded media will begin with /

collections:
  - name: 'docs' # Used in routes, e.g., /admin/collections/docs
    label: 'Docs' # Used in the UI
    folder: 'src' # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    extension: mdx
    slug: '{{title}}.stories' # Filename template, e.g., title.stories.mdx
    format: yaml-frontmatter
    frontmatter_delimiter: ['<!--', '-->']
    fields: # The fields for each document, usually in front matter
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown', modes: ['raw'] }
